// angular-frontend/src/app/shared/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { faFacebook, faTwitter, faLinkedin, faInstagram } from '@fortawesome/free-brands-svg-icons';
import { faArrowUp } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {
  faFacebook = faFacebook;
  faTwitter = faTwitter;
  faLinkedin = faLinkedin;
  faInstagram = faInstagram;
  faArrowUp = faArrowUp;

  scrollToTop(): void {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}
<footer class="footer">
  <div class="social-icons">
    <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" aria-label="Facebook">
      <fa-icon [icon]="faFacebook"></fa-icon>
    </a>
    <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" aria-label="Twitter">
      <fa-icon [icon]="faTwitter"></fa-icon>
    </a>
    <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
      <fa-icon [icon]="faLinkedin"></fa-icon>
    </a>
    <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
      <fa-icon [icon]="faInstagram"></fa-icon>
    </a>
  </div>
  <nav class="footer-nav">
    <a routerLink="/about">About</a>
    <a routerLink="/">Home</a>
    <a routerLink="/subscription">Services</a>
    <a routerLink="/team">Team</a>
    <a routerLink="/support">Contact</a>
    <a routerLink="/terms-of-service">Terms of Service</a>
    <a routerLink="/privacy-policy">Privacy Policy</a>
  </nav>
  <p class="copyright">©2025 | All Rights Reserved · Powered by GridX</p>
  <p class="tagline">Innovating Energy Solutions for a Sustainable Tomorrow</p>
  <button class="back-to-top-button" (click)="scrollToTop()">
    Back to Top <fa-icon [icon]="faArrowUp"></fa-icon>
  </button>
</footer>

// frontend/src/components/Footer.jsx
import { Box, Flex, Stack, IconButton, Text, Link as ChakraLink, Button } from '@chakra-ui/react';
import { FaFacebook, FaTwitter, FaLinkedin, FaInstagram, FaArrowUp } from 'react-icons/fa';
import { Link as RouterLink } from 'react-router-dom';

const Footer = () => {
  return (
    <Box
      bg="linear-gradient(90deg, #1c65d1, #2d8dee)"
      py={6}
      color="white"
      textAlign="center"
    >
      <Flex justify="center" mb={4}>
        <Stack direction="row" spacing={4}>
          <IconButton
            as="a"
            href="https://facebook.com"
            icon={<FaFacebook />}
            aria-label="Facebook"
          />
          <IconButton
            as="a"
            href="https://twitter.com"
            icon={<FaTwitter />}
            aria-label="Twitter"
          />
          <IconButton
            as="a"
            href="https://linkedin.com"
            icon={<FaLinkedin />}
            aria-label="LinkedIn"
          />
          <IconButton
            as="a"
            href="https://instagram.com"
            icon={<FaInstagram />}
            aria-label="Instagram"
          />
        </Stack>
      </Flex>
      <Flex justify="center" mb={4}>
        <Stack direction={{ base: 'column', md: 'row' }} spacing={4}>
          <ChakraLink as={RouterLink} to="/about" color="white" _hover={{ textDecoration: 'underline' }}>About</ChakraLink>
          <ChakraLink as={RouterLink} to="/" color="white" _hover={{ textDecoration: 'underline' }}>Home</ChakraLink>
          <ChakraLink as={RouterLink} to="/subscription" color="white" _hover={{ textDecoration: 'underline' }}>Services</ChakraLink>
          <ChakraLink as={RouterLink} to="/team" color="white" _hover={{ textDecoration: 'underline' }}>Team</ChakraLink>
          <ChakraLink as={RouterLink} to="/support" color="white" _hover={{ textDecoration: 'underline' }}>Contact</ChakraLink>
          <ChakraLink as={RouterLink} to="/terms-of-service" color="white" _hover={{ textDecoration: 'underline' }}>Terms of Service</ChakraLink>
          <ChakraLink as={RouterLink} to="/privacy-policy" color="white" _hover={{ textDecoration: 'underline' }}>Privacy Policy</ChakraLink>
        </Stack>
      </Flex>
      <Text fontSize="sm" mb={2} color="white" textShadow="1px 1px 2px rgba(0, 0, 0, 0.5)">©2025 | All Rights Reserved · Powered by GridX</Text>
      <Text fontSize="xs" mb={4} color="white" textShadow="1px 1px 2px rgba(0, 0, 0, 0.5)">Innovating Energy Solutions for a Sustainable Tomorrow</Text>
      <Button
        size="sm"
        onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
        rightIcon={<FaArrowUp />}
        variant="outline"
        colorScheme="whiteAlpha"
      >
        Back to Top
      </Button>
    </Box>
  );
};

export default Footer;
