// angular-frontend/src/app/shared/components/hero-typing-title/hero-typing-title.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-hero-typing-title',
  templateUrl: './hero-typing-title.component.html',
  styleUrls: ['./hero-typing-title.component.scss']
})
export class HeroTypingTitleComponent implements OnInit, OnDestroy {
  @Input() color: string = 'black';

  sequences: string[] = [
    'Monitor your energy in real-time ⚡️',
    'Predict future usage with AI 🧠',
    'Join the energy-smart community 🌍',
    'Beat load shedding schedules 🔌',
    'Optimize solar investments ☀️',
    'Track daily energy savings 💰',
    'Share power with neighbors 🤝',
    'Analyze consumption patterns 📊',
    'Get outage predictions ⚠️',
    'Compare community usage 👥',
    'Manage battery storage 🔋',
    'Receive smart grid alerts 📲',
    'Plan eco-friendly budgets 🌱'
  ];
  currentSequenceIndex: number = 0;
  typedText: string = '';
  isDeleting: boolean = false;
  typingSpeed: number = 100; // milliseconds per character
  deletingSpeed: number = 50; // milliseconds per character
  pauseTime: number = 2000; // milliseconds

  private typingTimeout: any;

  ngOnInit() {
    this.startTypingAnimation();
  }

  ngOnDestroy() {
    if (this.typingTimeout) {
      clearTimeout(this.typingTimeout);
    }
  }

  private startTypingAnimation() {
    const currentText = this.sequences[this.currentSequenceIndex];

    if (this.isDeleting) {
      // Deleting phase
      this.typedText = currentText.substring(0, this.typedText.length - 1);
      this.typingTimeout = setTimeout(() => this.startTypingAnimation(), this.deletingSpeed);
    } else {
      // Typing phase
      this.typedText = currentText.substring(0, this.typedText.length + 1);
      this.typingTimeout = setTimeout(() => this.startTypingAnimation(), this.typingSpeed);
    }

    if (!this.isDeleting && this.typedText === currentText) {
      // Pause at the end of typing
      this.typingTimeout = setTimeout(() => {
        this.isDeleting = true;
        this.startTypingAnimation();
      }, this.pauseTime);
    } else if (this.isDeleting && this.typedText === '') {
      // Move to next sequence after deleting
      this.isDeleting = false;
      this.currentSequenceIndex = (this.currentSequenceIndex + 1) % this.sequences.length;
      this.typingTimeout = setTimeout(() => this.startTypingAnimation(), 500); // Short pause before typing next
    }
  }
}
<h2 [ngStyle]="{'color': color}" style="text-align: center; font-size: 2rem;">
  <span style="display: inline-block; min-height: 1.2em;">
    {{ typedText }}
  </span>
</h2>

// frontend/src/components/HeroTypingTitle.jsx
import React from 'react';
import { TypeAnimation } from 'react-type-animation';
import { Heading } from '@chakra-ui/react';

function HeroTypingTitle({ color }) {
  return (
    <Heading size="2xl" color={color} textAlign="center">
      <TypeAnimation
        sequence={[
          'Monitor your energy in real-time ⚡️', 2000,
          'Predict future usage with AI 🧠', 2000,
          'Join the energy-smart community 🌍', 2000,
          'Beat load shedding schedules 🔌', 2000,
          'Optimize solar investments ☀️', 2000,
          'Track daily energy savings 💰', 2000,
          'Share power with neighbors 🤝', 2000,
          'Analyze consumption patterns 📊', 2000,
          'Get outage predictions ⚠️', 2000,
          'Compare community usage 👥', 2000,
          'Manage battery storage 🔋', 2000,
          'Receive smart grid alerts 📲', 2000,
          'Plan eco-friendly budgets 🌱', 2000,
          1000, // Final pause before restart
        ]}
        wrapper="span"
        cursor={true}
        repeat={Infinity}
        style={{
          display: 'inline-block',
          minHeight: '1.2em', // Prevent layout shift
        }}
      />
    </Heading>
  );
}

export default HeroTypingTitle;
