// angular-frontend/src/app/shared/components/navigation-panel/navigation-panel.component.ts
import { Component, OnInit, OnDestroy, Renderer2, ElementRef } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { 
  faHome,
  faArrowLeft,
  faSolarPanel,
  faUser,
  faBatteryFull,
  faCoins,
  faLightbulb,
  faTools,
  faTree,
  faSun,
  faUsers,
  faHandshake,
  faCreditCard
} from '@fortawesome/free-solid-svg-icons'; // Using solid icons for most
import { faLightbulb as faLightbulbRegular, faUser as faUserRegular, faSun as faSunRegular } from '@fortawesome/free-regular-svg-icons';
import { faRobot } from '@fortawesome/free-solid-svg-icons'; // For Bot/AI Suggestions
import { ThemeService } from '@services/theme.service'; // Changed path to use alias
import { Subscription } from 'rxjs';
import { CommonModule } from '@angular/common'; // Import CommonModule for ngIf/ngFor
import { RouterModule } from '@angular/router'; // Import RouterModule for routerLink
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome'; // Import FontAwesomeModule

@Component({
  selector: 'app-navigation-panel',
  templateUrl: './navigation-panel.component.html',
  styleUrls: ['./navigation-panel.component.scss'],
  standalone: true, // Make standalone
  imports: [
    CommonModule,
    RouterModule,
    FontAwesomeModule,
  ]
})
export class NavigationPanelComponent implements OnInit, OnDestroy {
  isVisible: boolean = false;
  currentPath: string = '';
  private routerSubscription: Subscription = new Subscription();
  private themeSubscription: Subscription = new Subscription();

  // Font Awesome icons
  faHome = faHome;
  faArrowLeft = faArrowLeft;
  faSolarPanel = faSolarPanel;
  faUser = faUser;
  faBatteryFull = faBatteryFull;
  faCoins = faCoins;
  faLightbulb = faLightbulb;
  faTools = faTools;
  faTree = faTree;
  faSun = faSun;
  faUsers = faUsers;
  faHandshake = faHandshake;
  faCreditCard = faCreditCard;
  faRobot = faRobot;

  // Chakra UI like colors
  triggerBgColor: string = 'white';
  triggerTextColor: string = 'teal.500';
  panelBg: string = 'white';
  panelBorderColor: string = 'gray.200';

  pages = [
    { name: 'Home', path: '/home', icon: this.faHome },
    { name: 'Dashboard', path: '/dashboard', icon: this.faSolarPanel },
    { name: 'Profile', path: '/profile', icon: this.faUser },
    { name: 'Settings', path: '/settings', icon: this.faTools },
    { name: 'Support', path: '/support', icon: this.faLightbulb },
    { name: 'About', path: '/about', icon: this.faUsers },
    { name: 'AI Suggestions', path: '/ai-suggestions', icon: this.faRobot },
    { name: 'Expenses', path: '/expenses', icon: this.faCoins },
    { name: 'Forum', path: '/forum', icon: this.faSun }, // Using faSun for Forum as a placeholder
    { name: 'Group Buying', path: '/group-buying', icon: this.faUsers },
    { name: 'Impact', path: '/impact', icon: this.faTree },
    { name: 'Notifications', path: '/notifications', icon: faLightbulbRegular }, // Using regular lightbulb
    { name: 'Personal User', path: '/personal-user', icon: faUserRegular }, // Using regular user
    { name: 'Refer', path: '/refer', icon: this.faHandshake },
    { name: 'Subscription', path: '/subscription', icon: this.faCreditCard },
    { name: 'Top Up', path: '/top-up', icon: this.faBatteryFull },
  ];

  constructor(
    private router: Router,
    private renderer: Renderer2,
    private el: ElementRef,
    private themeService: ThemeService
  ) { }

  ngOnInit(): void {
    // Subscribe to theme changes
    this.themeSubscription = this.themeService.colorMode$.subscribe((mode: 'light' | 'dark') => {
      this.triggerBgColor = this.themeService.getColorModeValue('white', 'rgba(0, 0, 0, 0.6)');
      this.triggerTextColor = this.themeService.getColorModeValue('teal.500', 'teal.300');
      this.panelBg = this.themeService.getColorModeValue('white', 'rgba(0, 0, 0, 0.6)');
      this.panelBorderColor = this.themeService.getColorModeValue('gray.200', 'gray.600');
    });

    // Add Back to Dashboard/Home conditionally based on current route
    this.routerSubscription = this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe(() => {
      this.currentPath = this.router.url;
      this.updateNavigationLinks();
    });
    this.updateNavigationLinks(); // Initial update
  }

  ngOnDestroy(): void {
    this.routerSubscription.unsubscribe();
    this.themeSubscription.unsubscribe();
  }

  private updateNavigationLinks(): void {
    const backToDashboardLink = { name: 'Back to Dashboard', path: '/dashboard', icon: this.faArrowLeft };
    const backToHomeLink = { name: 'Back to Home', path: '/home', icon: this.faHome };

    // Remove existing back links if present
    this.pages = this.pages.filter(page => 
      page.name !== 'Back to Dashboard' && page.name !== 'Back to Home'
    );

    // Add back links based on current route
    if (this.currentPath !== '/dashboard' && this.currentPath !== '/home') {
      // Assuming if not on home or dashboard, can go back to dashboard
      this.pages.push(backToDashboardLink);
    } else if (this.currentPath === '/dashboard') {
      // If on dashboard, can go back to home
      this.pages.push(backToHomeLink);
    }
  }

  navigateTo(path: string): void {
    this.router.navigate([path]);
    this.isVisible = false; // Hide panel after navigation
  }

  toggleVisibility(): void {
    this.isVisible = !this.isVisible;
  }
}
<div
  class="navigation-trigger-bubble"
  [ngStyle]="{
    'background': triggerBgColor,
    'border-color': panelBorderColor
  }"
  (click)="toggleVisibility()"
>
  <span class="menu-icon" [ngStyle]="{'color': triggerTextColor}">☰</span>
</div>

<div
  class="navigation-panel"
  [ngClass]="{'is-visible': isVisible}"
  [ngStyle]="{
    'background': panelBg,
    'border-color': panelBorderColor,
    'backdrop-filter': 'blur(16px)'
  }"
  (mouseenter)="isVisible = true"
  (mouseleave)="isVisible = false"
>
  <div class="navigation-header">
    <h2>Energy Dashboard</h2>
  </div>
  <div class="navigation-menu">
    <button
      *ngFor="let page of pages"
      class="navigation-item"
      (click)="navigateTo(page.path)"
    >
      <span class="icon">
        <fa-icon [icon]="page.icon"></fa-icon>
      </span>
      <span class="label">{{ page.name }}</span>
    </button>
  </div>
</div>

// frontend/src/components/NavigationPanel.jsx
import React, { useState, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom'; // Import to access navigation state
import './NavigationPanel.css'; // Import the CSS file for styling
import { FiHome, FiArrowLeft } from 'react-icons/fi'; // Keeping FiHome for Home
import { FaSolarPanel, FaUser, FaBatteryFull, FaCoins, FaRegLightbulb, FaTools, FaTree, FaLightbulb, FaRegSun, FaUsers, FaHandshake, FaCreditCard } from 'react-icons/fa';
import { Bot } from 'lucide-react'; // For AI Suggestions
import { useColorModeValue } from '@chakra-ui/react';  // Already present, but confirming it's used

const NavigationPanel = () => {
  const navigate = useNavigate();
  const panelRef = useRef(null);
  const location = useLocation();  // Get current location to check state

  // Add state for hover visibility
  const [isVisible, setIsVisible] = useState(false);

  // List of all pages with their names, paths, and icons
  const pages = [
    { name: 'Home', path: '/home', icon: <FiHome /> },  // Updated path to '/home' to match the route for HomePage.js
    { name: 'Dashboard', path: '/dashboard', icon: <FaSolarPanel /> },
    { name: 'Profile', path: '/profile', icon: <FaUser /> },
    { name: 'Settings', path: '/settings', icon: <FaTools /> },
    { name: 'Support', path: '/support', icon: <FaLightbulb /> },
    { name: 'About', path: '/about', icon: <FaUsers /> },  // Using FaUsers as a placeholder
    { name: 'AI Suggestions', path: '/ai-suggestions', icon: <Bot /> },
    { name: 'Expenses', path: '/expenses', icon: <FaCoins /> },
    { name: 'Forum', path: '/forum', icon: <FaRegSun /> },
    { name: 'Group Buying', path: '/group-buying', icon: <FaUsers /> },
    { name: 'Impact', path: '/impact', icon: <FaTree /> },
    { name: 'Notifications', path: '/notifications', icon: <FaRegLightbulb /> },
    { name: 'Personal User', path: '/personal-user', icon: <FaUser /> },  // Using FaUser as it's similar to Profile
    { name: 'Refer', path: '/refer', icon: <FaHandshake /> },
    { name: 'Subscription', path: '/subscription', icon: <FaCreditCard /> },
    { name: 'Top Up', path: '/top-up', icon: <FaBatteryFull /> },
    { name: 'Back to Dashboard', path: '/dashboard', icon: <FiArrowLeft /> },  // Assuming FiArrowLeft is imported; if not, use another icon like FiHome
    // Conditionally add Back to Home if coming from homepage
    ...(location.state?.from === 'home' ? [{ name: 'Back to Home', path: '/home', icon: <FiHome /> }] : []),
  ];

  // Remove drag-related functions
  // const handleDragStart = (e) => { ... };  // Removed to prevent dragging
  // const handleDrag = (e) => { ... };  // Removed to prevent dragging

  return (
    <>
      {/* Trigger Button */}
      <div
        style={{
          position: 'fixed',
          top: '20px',
          left: '10px',
          zIndex: '1000',
          cursor: 'pointer',
          padding: '10px',
          background: useColorModeValue('white', 'rgba(0, 0, 0, 0.6)'),  // Updated for frosted glass effect
          backdropFilter: 'blur(16px)',
          border: '1px solid',
          borderColor: useColorModeValue('gray.200', 'gray.600'),
          borderRadius: '50%',
          color: 'white',
        }}
        onMouseEnter={() => setIsVisible(true)}
      >
        ☰
      </div>

      <div
        className="navigation-panel"
        ref={panelRef}
        onMouseEnter={() => setIsVisible(true)}
        onMouseLeave={() => setIsVisible(false)}
        style={{
          transform: isVisible ? 'translateX(0)' : 'translateX(-100%)',
          transition: 'transform 0.3s ease-in-out',
          position: 'fixed',
          left: 0,
          top: 0,
          height: '100vh',
          zIndex: 1000,
          padding: '16px',
          background: useColorModeValue('white', 'rgba(0, 0, 0, 0.6)'),  // Updated for frosted glass effect
          backdropFilter: 'blur(16px)',
          border: '1px solid',
          borderColor: useColorModeValue('gray.200', 'gray.600'),
        }}
      >
        <div className="navigation-header">
          <h2>Energy Dashboard</h2>
        </div>
        <div className="navigation-menu">
          {pages.map((page) => (
            <button
              key={page.name}
              className="navigation-item"
              onClick={() => navigate(page.path)}
            >
              <span className="icon">{page.icon}</span>
              <span className="label">{page.name}</span>
            </button>
          ))}
        </div>
      </div>
    </>
  );
};

export default NavigationPanel;
