// angular-frontend/src/app/shared/components/supportbot/supportbot.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, Renderer2 } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ThemeService } from '../../../services/theme.service';
import { ToastService } from '../../../services/toast.service';
import { AiAgentService } from '../../../services/ai-agent.service';
import {
  faPaperPlane,
  faTimes,
  faCommentDots,
  faVolumeMute,
  faVolumeUp,
  faMicrophone
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { Subscription } from 'rxjs';

interface ChatMessage {
  text: string;
  sender: 'user' | 'bot';
  thinking?: boolean;
  typing?: boolean;
}

declare const webkitSpeechRecognition: any; // Declare for TypeScript

@Component({
  selector: 'app-supportbot',
  templateUrl: './supportbot.component.html',
  styleUrls: ['./supportbot.component.scss'],
  standalone: true,
  imports: [CommonModule, FormsModule, FontAwesomeModule]
})
export class SupportbotComponent implements OnInit, OnDestroy {
  @ViewChild('messagesEnd') messagesEndRef!: ElementRef;

  // Icons
  faPaperPlane = faPaperPlane;
  faTimes = faTimes;
  faCommentDots = faCommentDots;
  faVolumeMute = faVolumeMute;
  faVolumeUp = faVolumeUp;
  faMicrophone = faMicrophone;

  isOpen: boolean = false;
  messages: ChatMessage[] = [];
  inputMessage: string = '';
  isLoading: boolean = false;
  typing: boolean = false;
  hasSpokenLangaGreeting: boolean = false;
  isMuted: boolean = false;
  isSpeaking: boolean = false; // For animation
  isListening: boolean = false;
  recognitionActiveRef: boolean = false;

  private recognition: any;
  private selectedVoice: SpeechSynthesisVoice | null = null;
  private typingInterval: any;
  private themeSubscription: Subscription = new Subscription();

  // Theme-related properties
  bubbleBgColor: string = '';
  headerBgGradient: string = '';
  headerColor: string = '';
  chatBg: string = '';
  userBgColor: string = '';
  botBgColor: string = '';
  textColor: string = '';
  inputBg: string = '';
  inputBorderColor: string = '';
  inputFocusBorderColor: string = '';
  inputAreaBg: string = '';
  inputAreaBorderColor: string = '';

  langaImage: string = "https://placehold.co/150x150/008080/ffffff?text=Langa"; // Placeholder URL
  langaGreeting: string = "Hi! I'm Langa. How can I help you today?";

  constructor(
    private themeService: ThemeService,
    private toastService: ToastService,
    private aiAgentService: AiAgentService,
    private renderer: Renderer2
  ) {
    // Initialize SpeechRecognition if available
    if ('SpeechRecognition' in window || 'webkitSpeechRecognition' in window) {
      this.recognition = new (window as any).SpeechRecognition();
      this.recognition.continuous = false;
      this.recognition.interimResults = false;
      this.recognition.lang = 'en-US';

      this.recognition.onresult = (event: any) => {
        const speech = event.results[0][0].transcript;
        this.inputMessage = '';
        this.isListening = false;
        this.recognitionActiveRef = false;
        this.handleSendMessage(speech);
      };

      this.recognition.onend = () => {
        this.isListening = false;
        this.recognitionActiveRef = false;
      };

      this.recognition.onerror = (event: any) => {
        console.error('Speech recognition error:', event.error);
        this.toastService.show({
          title: 'Voice Input Failed',
          description: "Sorry, I couldn't process your voice message. Try again or type your message.",
          status: 'error',
          duration: 3000,
          isClosable: true,
          position: 'bottom',
        });
        this.isListening = false;
        this.recognitionActiveRef = false;
      };
    }
  }

  ngOnInit(): void {
    this.setupThemeSubscription();
    this.setupVoiceSelection();

    // Initial message if needed, or when opened
    if (this.isOpen && !this.hasSpokenLangaGreeting && !this.isMuted) {
      // This is handled by toggleOpen or after messages are set
    }
  }

  ngOnDestroy(): void {
    this.themeSubscription.unsubscribe();
    if (this.typingInterval) {
      clearInterval(this.typingInterval);
    }
    if (this.recognitionActiveRef) {
      this.recognition.stop();
    }
    window.speechSynthesis.cancel();
  }

  private setupThemeSubscription(): void {
    this.themeSubscription = this.themeService.colorMode$.subscribe(mode => {
      this.bubbleBgColor = this.themeService.getColorModeValue('white', 'gray.800');
      this.headerBgGradient = this.themeService.getColorModeValue('linear-gradient(to right, #38B2AC, #319795)', 'linear-gradient(to right, #2D3748, #4A5568)');
      this.headerColor = this.themeService.getColorModeValue('white', 'white');
      this.chatBg = this.themeService.getColorModeValue('gray.50', 'gray.800');
      this.userBgColor = this.themeService.getColorModeValue('blue.100', 'blue.800');
      this.botBgColor = this.themeService.getColorModeValue('gray.100', 'gray.700');
      this.textColor = this.themeService.getColorModeValue('black', 'white');
      this.inputBg = this.themeService.getColorModeValue('white', 'gray.700');
      this.inputBorderColor = this.themeService.getColorModeValue('gray.200', 'gray.600');
      this.inputFocusBorderColor = this.themeService.getColorModeValue('teal.400', 'teal.400');
      this.inputAreaBg = this.themeService.getColorModeValue('gray.100', 'gray.900');
      this.inputAreaBorderColor = this.themeService.getColorModeValue('gray.200', 'gray.700');
    });
  }

  private setupVoiceSelection(): void {
    const setVoice = () => {
      this.selectedVoice = this.pickSiriLikeVoice();
    };
    setVoice();
    if (typeof window !== 'undefined') {
      window.speechSynthesis.onvoiceschanged = setVoice;
    }
  }

  private pickSiriLikeVoice(): SpeechSynthesisVoice | null {
    if (typeof window === 'undefined' || !window.speechSynthesis) return null;
    const voices = window.speechSynthesis.getVoices();
    let siriVoice = voices.find(v => v.lang && v.lang.includes('en-US') && (v.name === 'Samantha' || v.name === 'Alex'));
    if (!siriVoice) {
      siriVoice = voices.find(v => v.lang && v.lang.includes('en-US'));
    }
    if (!siriVoice) {
      siriVoice = voices.find(v => v.lang && v.lang.startsWith('en'));
    }
    return siriVoice || null;
  }

  speakReply(text: string): void {
    if (this.isMuted || typeof window === 'undefined' || !window.speechSynthesis) return;
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = this.selectedVoice?.lang || 'en-US';
    utterance.voice = this.selectedVoice || null;
    utterance.pitch = 1.1;
    utterance.rate = 0.95;
    window.speechSynthesis.cancel();
    this.isSpeaking = true;
    utterance.onend = () => this.isSpeaking = false;
    utterance.onerror = () => this.isSpeaking = false;
    window.speechSynthesis.speak(utterance);
  }

  toggleOpen(): void {
    this.isOpen = !this.isOpen;
    if (this.isOpen) {
      if (!this.hasSpokenLangaGreeting && !this.isMuted) {
        window.speechSynthesis.cancel();
        this.messages = [{ text: this.langaGreeting, sender: 'bot' }];
        this.speakReply(this.langaGreeting);
        this.hasSpokenLangaGreeting = true;
      } else if (this.messages.length === 0) {
        this.messages = [{ text: this.langaGreeting, sender: 'bot' }];
      }
    } else {
      window.speechSynthesis.cancel();
      this.isListening = false; // Stop listening when closing chatbot
      this.recognitionActiveRef = false;
      if (this.recognition) {
        this.recognition.stop();
      }
    }
  }

  toggleMute(): void {
    this.isMuted = !this.isMuted;
    if (this.isMuted) {
      window.speechSynthesis.cancel();
    }
  }

  async handleSendMessage(messageText: string = this.inputMessage.trim()): Promise<void> {
    if (!messageText) return;

    this.messages.push({ text: messageText, sender: 'user' });
    this.inputMessage = '';
    this.isLoading = true;
    this.typing = true;

    // Add 'Thinking...' message
    this.messages.push({ text: '🤔 Thinking...', sender: 'bot', thinking: true });
    this.scrollToBottom();

    await new Promise(res => setTimeout(res, 800));

    // Replace 'Thinking...' with animated typing dots
    this.messages = this.messages.map(msg => 
      msg.thinking ? { ...msg, text: 'Langa is typing', typing: true } : msg
    );
    this.scrollToBottom();

    let dotCount = 0;
    this.typingInterval = setInterval(() => {
      this.messages = this.messages.map(msg => 
        msg.typing ? { ...msg, text: `Langa is typing${'.'.repeat(dotCount % 4)}` } : msg
      );
      dotCount++;
      this.scrollToBottom();
    }, 400);

    let botReply: string;
    try {
      const data = await this.aiAgentService.sendMessage(messageText).toPromise();
      botReply = data?.reply || data?.response || "Sorry, I didn't get a reply.";
    } catch (error) {
      console.error('Error:', error);
      botReply = "I apologize, but I'm having trouble connecting. Please try again.";
      this.toastService.show({
        title: 'Error',
        description: 'Failed to get response from server',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    } finally {
      clearInterval(this.typingInterval);
      this.isLoading = false;
      this.typing = false;
    }

    this.messages = this.messages.map(msg => 
      msg.typing || msg.thinking ? { text: botReply, sender: 'bot' } : msg
    );
    this.scrollToBottom();
    this.speakReply(botReply);
  }

  handleMicClick(): void {
    if (!this.recognition) {
      this.toastService.show({
        title: 'Browser Not Supported',
        description: "Sorry, your browser doesn't support voice-to-text.",
        status: 'error',
        duration: 3000,
        isClosable: true,
        position: 'bottom',
      });
      return;
    }

    if (this.isListening || this.recognitionActiveRef) {
      this.recognition.stop();
      this.isListening = false;
      this.recognitionActiveRef = false;
    } else {
      try {
        this.recognition.start();
        this.isListening = true;
        this.recognitionActiveRef = true;
      } catch (e: any) {
        if (e.name === 'AbortError') {
          // User agent is already listening, do nothing.
        } else {
          console.error('Speech recognition start error:', e);
        }
        this.isListening = true; // Still show as listening if already started
        this.recognitionActiveRef = true;
      }
    }
  }

  onKeyPress(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.handleSendMessage();
    }
  }

  private scrollToBottom(): void {
    setTimeout(() => {
      if (this.messagesEndRef) {
        this.messagesEndRef.nativeElement.scrollIntoView({ behavior: 'smooth', block: 'end' });
      }
    }, 0); // Small delay to allow DOM to update
  }
}
<div class="floating-bubble-container" *ngIf="!isOpen">
  <button
    class="floating-bubble"
    aria-label="Chat with Langa"
    (click)="toggleOpen()"
    [ngStyle]="{'background-color': bubbleBgColor}"
  >
    <fa-icon [icon]="faCommentDots"></fa-icon>
  </button>
</div>

<div
  class="chatbot-card"
  *ngIf="isOpen"
  [ngStyle]="{
    'background-color': chatBg
  }"
>
  <div
    class="chatbot-header"
    [ngStyle]="{
      'background': headerBgGradient,
      'color': headerColor
    }"
  >
    <div class="avatar-name-group">
      <img
        [src]="langaImage"
        alt="Langa Avatar"
        class="avatar"
        [ngClass]="{'bot-speaking': isSpeaking}"
      />
      <h3 class="bot-name">Langa</h3>
    </div>
    <div class="header-buttons">
      <button
        class="icon-button"
        (click)="toggleMute()"
        [attr.aria-label]="isMuted ? 'Unmute Langa' : 'Mute Langa'"
        [attr.title]="isMuted ? 'Unmute voice replies' : 'Mute voice replies'"
      >
        <fa-icon [icon]="isMuted ? faVolumeMute : faVolumeUp"></fa-icon>
      </button>
      <button
        class="icon-button"
        (click)="toggleOpen()"
      >
        <fa-icon [icon]="faTimes"></fa-icon>
      </button>
    </div>
  </div>

  <div class="messages-container">
    <div
      *ngFor="let message of messages; let i = index"
      class="message-row"
      [ngClass]="{'user': message.sender === 'user', 'bot': message.sender === 'bot'}"
    >
      <img *ngIf="message.sender === 'bot'" [src]="langaImage" alt="Bot Avatar" class="message-avatar" />
      <div
        class="message-bubble"
        [ngStyle]="{
          'background-color': message.sender === 'bot' ? botBgColor : userBgColor,
          'color': textColor
        }"
      >
        {{ message.text }}
      </div>
      <div *ngIf="message.sender === 'user'" class="message-avatar user-avatar"></div>
    </div>
    <div #messagesEnd></div>
  </div>

  <div class="input-area"
    [ngStyle]="{
      'background-color': inputAreaBg,
      'border-color': inputAreaBorderColor
    }"
  >
    <input
      type="text"
      [(ngModel)]="inputMessage"
      (keypress)="onKeyPress($event)"
      placeholder="Type your message..."
      class="message-input"
      [disabled]="isLoading || isListening"
      [ngStyle]="{
        'background-color': inputBg,
        'border-color': inputBorderColor,
        'color': textColor
      }"
    />
    <button
      class="mic-button"
      (click)="handleMicClick()"
      [ngClass]="{'listening': isListening}"
    >
      <fa-icon [icon]="faMicrophone"></fa-icon>
    </button>
    <button
      class="send-button"
      (click)="handleSendMessage()"
      [disabled]="isLoading || !inputMessage.trim() || isListening"
    >
      <fa-icon [icon]="faPaperPlane"></fa-icon>
    </button>
  </div>
</div>

// frontend/src/components/Supportbot.jsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import {
  Box,
  Flex,
  VStack,
  HStack,
  IconButton,
  Input,
  Heading,
  Text,
  useToast,
  Avatar,
  useColorModeValue,
  Button,
} from '@chakra-ui/react';
import { FaPaperPlane, FaTimes, FaCommentDots, FaVolumeMute, FaVolumeUp } from 'react-icons/fa';
// Replaced local image import with a placeholder URL
// If you have a specific image, you'll need to host it or use a base64 string (not recommended for large images)
const langaImage = "https://placehold.co/150x150/008080/ffffff?text=Langa";

// Add SpeechRecognition support
const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
const recognition = SpeechRecognition ? new SpeechRecognition() : null;

let selectedVoice = null;

function pickSiriLikeVoice() {
  const voices = window.speechSynthesis.getVoices();
  // Prefer 'Samantha', 'Alex', or any en-US Siri-like voice
  let siriVoice = voices.find(v => v.lang && v.lang.includes('en-US') && (v.name === 'Samantha' || v.name === 'Alex'));
  if (!siriVoice) {
    siriVoice = voices.find(v => v.lang && v.lang.includes('en-US'));
  }
  if (!siriVoice) {
    siriVoice = voices.find(v => v.lang && v.lang.startsWith('en'));
  }
  return siriVoice || null;
}

// Set up voice selection on load and on voiceschanged
function useSiriLikeVoice() {
  useEffect(() => {
    function setVoice() {
      selectedVoice = pickSiriLikeVoice();
    }
    setVoice();
    window.speechSynthesis.onvoiceschanged = setVoice;
    return () => {
      window.speechSynthesis.onvoiceschanged = null;
    };
  }, []);
}

const langaGreeting = "Hi! I'm Langa. How can I help you today?";

const SupportBot = () => {
  console.log('SupportBot component is mounting');

  const [isOpen, setIsOpen] = useState(false); // Must be false
  const [messages, setMessages] = useState([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [typing, setTyping] = useState(false); // State for "Bot is typing..."
  const [hasSpokenLangaGreeting, setHasSpokenLangaGreeting] = useState(false);
  const [isMuted, setIsMuted] = useState(false); // Mute/unmute state

  // --- Langa Voice Logic ---
  const [isSpeaking, setIsSpeaking] = useState(false); // For animation

  // State for voice-to-text
  const [isListening, setIsListening] = useState(false);
  const recognitionActiveRef = useRef(false);

  useSiriLikeVoice();

  // Voice reply function for Langa
  const speakReply = useCallback((text) => {
    if (isMuted) return;
    if (!window.speechSynthesis) return;
    const utterance = new window.SpeechSynthesisUtterance(text);
    utterance.lang = selectedVoice?.lang || 'en-US';
    utterance.voice = selectedVoice || null;
    utterance.pitch = 1.1;
    utterance.rate = 0.95;
    window.speechSynthesis.cancel(); // Always cancel any ongoing speech
    setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    window.speechSynthesis.speak(utterance);
  }, [isMuted]);

  // Langa greeting ONLY when chatbot is opened for the first time per session (not on app load)
  useEffect(() => {
    if (isOpen && !hasSpokenLangaGreeting && !isMuted) {
      window.speechSynthesis.cancel();
      speakReply(langaGreeting);
      setHasSpokenLangaGreeting(true);
    }
    if (isOpen && isMuted) {
      window.speechSynthesis.cancel();
    }
  }, [isOpen, hasSpokenLangaGreeting, isMuted, speakReply]);

  // Call speakReply whenever a new bot message is added (and not muted)
  useEffect(() => {
    if (messages.length === 0) return;
    const lastMsg = messages[messages.length - 1];
    if (lastMsg.sender === 'bot' && lastMsg.text && !lastMsg.typing && !lastMsg.thinking && !isMuted) {
      speakReply(lastMsg.text);
    }
    // eslint-disable-next-line
  }, [messages, isMuted, speakReply]);

  const toast = useToast();
  const messagesEndRef = useRef(null); // Ref to scroll to the latest message

  const bgColor = useColorModeValue('gray.100', 'gray.700');
  const userBgColor = useColorModeValue('blue.100', 'blue.800');
  const textColor = useColorModeValue('black', 'white');

  const API_BASE_URL = 'https://for-the-100th-time-1.onrender.com';

  // Scroll to the latest message whenever messages state updates
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSendMessage = async (messageText = null) => {
    const textToSend = messageText || inputMessage.trim();
    if (!textToSend) return;

    // Add user message immediately
    setMessages(prev => [...prev, { text: textToSend, sender: 'user' }]);
    setInputMessage(''); // Clear input
    setIsLoading(true); // Disable input/send button
    setTyping(true); // Show "Bot is typing..."

    // Show '🤔 Thinking...' immediately
    setMessages(prev => [...prev, { text: '🤔 Thinking...', sender: 'bot', thinking: true }]);

    // Simulate typing effect
    await new Promise(res => setTimeout(res, 800)); // Short delay before typing

    // Replace '🤔 Thinking...' with animated typing dots
    setMessages(prev => {
      const updated = [...prev];
      const lastIdx = updated.findIndex(m => m.thinking);
      if (lastIdx !== -1) {
        updated[lastIdx] = { ...updated[lastIdx], text: 'Langa is typing', typing: true };
      }
      return updated;
    });

    // Animate typing effect (3 dots)
    let dotCount = 0;
    const typingInterval = setInterval(() => {
      setMessages(prev => {
        const updated = [...prev];
        const lastIdx = updated.findIndex(m => m.typing);
        if (lastIdx !== -1) {
          updated[lastIdx] = { ...updated[lastIdx], text: `Langa is typing${'.'.repeat(dotCount % 4)}` };
        }
        return updated;
      });
      dotCount++;
    }, 400);

    let data;
    try {
      const response = await fetch(`${API_BASE_URL}/api/ai-agent`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: textToSend }),
      });
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      data = await response.json();
    } catch (error) {
      console.error('Error:', error);
      data = { response: "I apologize, but I'm having trouble connecting. Please try again." };
      toast({
        title: 'Error',
        description: 'Failed to get response from server',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    } finally {
      clearInterval(typingInterval);
      setIsLoading(false);
      setTyping(false);
    }

    const botReply = data.reply || data.response || "Sorry, I didn't get a reply.";
    setMessages(prev => {
      const updated = [...prev];
      const lastIdx = updated.findIndex(m => m.typing || m.thinking);
      if (lastIdx !== -1) {
        updated[lastIdx] = { text: botReply, sender: 'bot' };
      } else {
        updated.push({ text: botReply, sender: 'bot' });
      }
      return updated;
    });
  };

  // Voice-to-text mic logic
  const handleMicClick = () => {
    if (!recognition) {
      setMessages(prev => [...prev, { text: "Sorry, your browser doesn't support voice-to-text.", sender: 'bot' }]);
      return;
    }
    if (isListening || recognitionActiveRef.current) {
      recognition.stop();
      setIsListening(false);
      recognitionActiveRef.current = false;
      return;
    }
    // Only start if not already listening
    try {
      recognition.start();
      setIsListening(true);
      recognitionActiveRef.current = true;
    } catch (e) {
      // If already started, just ignore
      setIsListening(true);
      recognitionActiveRef.current = true;
    }
    recognition.onresult = (event) => {
      const speech = event.results[0][0].transcript;
      setInputMessage('');
      setIsListening(false);
      recognitionActiveRef.current = false;
      handleSendMessage(speech);
    };
    recognition.onend = () => {
      setIsListening(false);
      recognitionActiveRef.current = false;
    };
    recognition.onerror = (event) => {
      console.error('Speech recognition error:', event.error);
      setMessages(prev => [...prev, { text: "Sorry, I couldn't process your voice message. Try again or type your message.", sender: 'bot' }]);
      setIsListening(false);
      recognitionActiveRef.current = false;
    };
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <>
      {/* Floating Bubble (always visible, but hidden when chat is open) */}
      {!isOpen && (
        <Box
          position="fixed"
          bottom="24px"
          right="24px"
          zIndex="9999"
        >
          <IconButton
            aria-label="Chat with Langa"
            icon={<FaCommentDots />}
            boxSize="56px" // Explicitly set box size to match ThemeToggleButton
            fontSize="2xl" // Explicitly set font size to match ThemeToggleButton
            colorScheme="teal"
            isRound
            boxShadow="lg"
            onClick={() => {
              setIsOpen(true);
              setHasSpokenLangaGreeting(false); // Reset greeting for new session
              setMessages([{ text: "Hi! I'm Langa. How can I help you today?", sender: 'bot' }]);
            }}
          />
        </Box>
      )}

      {/* Chatbot Card (only visible when open) */}
      {isOpen && (
        <Box
          position="fixed"
          bottom="24px"
          right="24px"
          zIndex="9999"
          width={["95vw", "350px"]}
          maxWidth="100vw"
          height="520px"
          bg="white"
          borderRadius="2xl"
          boxShadow="2xl"
          overflow="hidden"
          display="flex"
          flexDirection="column"
        >
          <Flex
            align={"center"}
            justify={"space-between"}
            bgGradient={"linear(to-r, teal.500, teal.400)"}
            color={"white"}
            p={4}
            boxShadow={"md"}
          >
            <HStack>
              <Avatar size="md" border="2px solid white" src={langaImage} className={isSpeaking ? 'bot-speaking' : ''} />
              <Heading size="md" fontWeight="bold" letterSpacing="wide">
                Langa
              </Heading>
            </HStack>
            <HStack>
              <IconButton
                icon={isMuted ? <FaVolumeMute /> : <FaVolumeUp />}
                variant="ghost"
                color="white"
                onClick={() => {
                  setIsMuted(m => {
                    if (!m) window.speechSynthesis.cancel();
                    return !m;
                  });
                }}
                size="sm"
                aria-label={isMuted ? 'Unmute Langa' : 'Mute Langa'}
                _hover={{ bg: "teal.600" }}
                title={isMuted ? 'Unmute voice replies' : 'Mute voice replies'}
              />
              <IconButton
                icon={<FaTimes />}
                variant="ghost"
                color="white"
                onClick={() => setIsOpen(false)}
                size="sm"
                _hover={{ bg: "teal.600" }}
              />
            </HStack>
          </Flex>

          {/* Messages */}
          <VStack
            flex={1}
            spacing={3}
            px={3}
            py={2}
            overflowY="auto"
            align="stretch"
            bg="gray.50"
            sx={{
              "&::-webkit-scrollbar": {
                width: "6px",
                background: "#e0e0e0",
                borderRadius: "8px"
              },
              "&::-webkit-scrollbar-thumb": {
                background: "#b2b2b2",
                borderRadius: "8px"
              }
            }}
          >
            {messages.map((message, idx) => (
              <Flex key={idx} justify={message.sender === 'bot' ? 'flex-start' : 'flex-end'} align="center">
                {message.sender === 'bot' && <Avatar name="SolarBot" src={langaImage} size="sm" mr={2} />}
                <Box bg={message.sender === 'bot' ? bgColor : userBgColor} color={textColor} p={3} borderRadius="md">
                  {message.text}
                </Box>
                {message.sender === 'user' && <Avatar name="You" bg="blue.500" size="sm" ml={2} />}
              </Flex>
            ))}
            {/* Thinking state display */}
            {typing && (
              <Flex justify="flex-start" align="center">
                <Avatar name="SolarBot" src={langaImage} size="sm" mr={2} />
                <Text fontStyle="italic" color="gray.500">Langa is typing...</Text>
              </Flex>
            )}
            <div ref={messagesEndRef} /> {/* For auto-scrolling */}
          </VStack>

          {/* Input */}
          <Flex
            p={3}
            bg="gray.100"
            borderTop="1px solid"
            borderColor="gray.200"
            align="center"
          >
            <Input
              value={inputMessage}
              onChange={e => setInputMessage(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Type your message..."
              size="md"
              bg="white"
              borderRadius="full"
              mr={2}
              _focus={{ borderColor: "teal.400" }}
              disabled={isLoading || isListening} /* Disable during loading/recording */
            />
            <Button
              onClick={handleMicClick}
              colorScheme={isListening ? "red" : "teal"}
              borderRadius="full"
              mr={2}
            >
              {isListening ? '🎤 Listening… Tap to Stop' : '🎙️ Speak'}
            </Button>
            <IconButton
              colorScheme="teal"
              aria-label="Send message"
              icon={<FaPaperPlane />}
              onClick={() => handleSendMessage()}
              isLoading={isLoading}
              disabled={isLoading || !inputMessage.trim() || isListening} /* Disable during loading/recording or if no text */
              borderRadius="full"
            />
          </Flex>
        </Box>
      )}
    </>
  );
};

export default SupportBot;
