// frontend/src/components/AITipsPanel.jsx
import React, { useState } from 'react';
import {
  Box,
  Heading,
  Text,
  IconButton,
  Flex,
  useColorModeValue,
  Badge,
  Avatar,
  VStack,
  HStack,
  Divider
} from '@chakra-ui/react';
import { FiChevronLeft, FiChevronRight, FiDollarSign, FiSun, FiBattery } from 'react-icons/fi';
import PropTypes from 'prop-types';

const AITipsPanel = () => {
  const [currentTipIndex, setCurrentTipIndex] = useState(0);
  const headingColor = useColorModeValue('gray.800', 'whiteAlpha.900');
  const accentColor = useColorModeValue('blue.500', 'blue.300');

  const energyTips = [
    {
      title: "Peak Hour Optimization",
      content: "Shift high-energy activities to off-peak hours (10PM-6AM) to reduce costs by up to 30%",
      category: "Savings",
      icon: FiDollarSign,
      badgeColor: "green"
    },
    {
      title: "Solar Utilization",
      content: "Increase solar self-consumption by scheduling pool pumps and appliances during daylight hours",
      category: "Efficiency",
      icon: FiSun,
      badgeColor: "orange"
    },
    {
      title: "Battery Management",
      content: "Maintain battery charge between 20-80% for optimal lifespan and performance",
      category: "Maintenance",
      icon: FiBattery,
      badgeColor: "blue"
    }
  ];

  const handleNextTip = () => {
    setCurrentTipIndex((prev) => (prev + 1) % energyTips.length);
  };

  const handlePrevTip = () => {
    setCurrentTipIndex((prev) => (prev - 1 + energyTips.length) % energyTips.length);
  };

  return (
    <Box
      bg={useColorModeValue('linear-gradient(to bottom right, #EBF8FF, #BEE3F8)', 'linear-gradient(to bottom right, #1A202C, #2D3748)')}
      p={6}
      borderRadius="xl"
      boxShadow="xl"
      borderWidth="1px"
      borderColor={useColorModeValue('gray.700', 'gray.600')}
      height="100%"
      minHeight="250px"
      display="flex"
      flexDirection="column"
    >
      <Flex justify="space-between" align="center" mb={4}>
        <Heading size="md" color={headingColor}>
          AI Energy Tips
        </Heading>
        <Badge colorScheme="blue" variant="subtle">
          {currentTipIndex + 1}/{energyTips.length}
        </Badge>
      </Flex>

      <VStack spacing={4} align="stretch">
        <Flex alignItems="center" mb={2}>
          <Avatar 
            size="sm" 
            name="AI Tip Icon"
            bg={accentColor}
            color="white"
            mr={3}
            _hover={{ transform: 'scale(1.05)' }}
            transition="transform 0.2s"
          />
          <Text fontSize="lg" fontWeight="bold" color={useColorModeValue('gray.800', 'white')}>
            {energyTips[currentTipIndex].title}
          </Text>
        </Flex>
        
        <Text fontSize="md" fontWeight="medium" color={useColorModeValue('gray.600', 'gray.300')} lineHeight="tall">
          {energyTips[currentTipIndex].content}
        </Text>

        <Divider />

        <Flex justify="space-between" align="center" pt={2}>
          <Badge 
            colorScheme={energyTips[currentTipIndex].badgeColor} 
            variant="subtle"
            fontSize="xs"
          >
            {energyTips[currentTipIndex].category}
          </Badge>
          
          <HStack>
            <IconButton
              icon={<FiChevronLeft />}
              size="sm"
              variant="ghost"
              onClick={handlePrevTip}
              aria-label="Previous tip"
              _hover={{ color: accentColor }}
            />
            <IconButton
              icon={<FiChevronRight />}
              size="sm"
              variant="ghost"
              onClick={handleNextTip}
              aria-label="Next tip"
            />
          </HStack>
        </Flex>
      </VStack>
    </Box>
  );
};

AITipsPanel.propTypes = {
  tips: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string.isRequired,
      content: PropTypes.string.isRequired,
      category: PropTypes.string.isRequired,
      icon: PropTypes.elementType.isRequired,
      badgeColor: PropTypes.string.isRequired
    })
  )
};

export default AITipsPanel;

// angular-frontend/src/app/shared/components/ai-tips-panel/ai-tips-panel.component.ts
import { Component, OnInit } from '@angular/core';
import { ThemeService } from '@services/theme.service'; // Changed path to use alias
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { faDollarSign, faSun, faBatteryFull, faChevronLeft, faChevronRight } from '@fortawesome/free-solid-svg-icons';
import { CommonModule } from '@angular/common'; // Import CommonModule for ngClass/ngStyle
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome'; // Import FontAwesomeModule

interface EnergyTip {
  title: string;
  content: string;
  category: string;
  icon: IconDefinition;
  badgeColor: string;
}

@Component({
  selector: 'app-ai-tips-panel',
  templateUrl: './ai-tips-panel.component.html',
  styleUrls: ['./ai-tips-panel.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FontAwesomeModule,
  ]
})
export class AiTipsPanelComponent implements OnInit {
  currentTipIndex: number = 0;
  energyTips: EnergyTip[] = [
    {
      title: "Peak Hour Optimization",
      content: "Shift high-energy activities to off-peak hours (10PM-6AM) to reduce costs by up to 30%",
      category: "Savings",
      icon: faDollarSign,
      badgeColor: "green"
    },
    {
      title: "Solar Utilization",
      content: "Increase solar self-consumption by scheduling pool pumps and appliances during daylight hours",
      category: "Efficiency",
      icon: faSun,
      badgeColor: "orange"
    },
    {
      title: "Battery Management",
      content: "Maintain battery charge between 20-80% for optimal lifespan and performance",
      category: "Maintenance",
      icon: faBatteryFull,
      badgeColor: "blue"
    }
  ];

  faArrowLeft = faChevronLeft;
  faArrowRight = faChevronRight;

  headingColor: string = '';
  accentColor: string = '';
  textColorPrimary: string = '';
  textColorSecondary: string = '';
  boxBgGradient: string = '';
  boxBorderColor: string = '';

  constructor(private themeService: ThemeService) { }

  ngOnInit(): void {
    this.themeService.colorMode$.subscribe((mode: 'light' | 'dark') => {
      this.headingColor = this.themeService.getColorModeValue('gray.800', 'whiteAlpha.900');
      this.accentColor = this.themeService.getColorModeValue('blue.500', 'blue.300');
      this.textColorPrimary = this.themeService.getColorModeValue('gray.800', 'white');
      this.textColorSecondary = this.themeService.getColorModeValue('gray.600', 'gray.300');
      this.boxBgGradient = this.themeService.getColorModeValue(
        'linear-gradient(to bottom right, #EBF8FF, #BEE3F8)',
        'linear-gradient(to bottom right, #1A202C, #2D3748)'
      );
      this.boxBorderColor = this.themeService.getColorModeValue('gray.700', 'gray.600');
    });
  }

  handleNextTip(): void {
    this.currentTipIndex = (this.currentTipIndex + 1) % this.energyTips.length;
  }

  handlePrevTip(): void {
    this.currentTipIndex = (this.currentTipIndex - 1 + this.energyTips.length) % this.energyTips.length;
  }

  onAvatarHover(event: Event, scale: string): void {
    const target = event.target as HTMLElement;
    if (target) {
      target.style.transform = scale;
    }
  }
}
<div
  class="ai-tips-panel"
  [ngStyle]="{
    'background-image': boxBgGradient,
    'border-color': boxBorderColor
  }"
>
  <div class="header-flex">
    <h2 class="heading" [ngStyle]="{'color': headingColor}">
      AI Energy Tips
    </h2>
    <span class="badge" [ngClass]="{
      'badge-blue': true
    }">
      {{ currentTipIndex + 1 }}/{{ energyTips.length }}
    </span>
  </div>

  <div class="tip-content-vstack">
    <div class="tip-flex-header">
      <div
        class="avatar"
        [ngStyle]="{'background-color': accentColor}"
        (mouseenter)="onAvatarHover($event, 'scale(1.05)')"
        (mouseleave)="onAvatarHover($event, 'scale(1)')"
      >
        <fa-icon [icon]="energyTips[currentTipIndex].icon"></fa-icon>
      </div>
      <p class="tip-title" [ngStyle]="{'color': textColorPrimary}">
        {{ energyTips[currentTipIndex].title }}
      </p>
    </div>

    <p class="tip-content" [ngStyle]="{'color': textColorSecondary}">
      {{ energyTips[currentTipIndex].content }}
    </p>

    <hr class="divider" />

    <div class="tip-footer-flex">
      <span class="badge" [ngClass]="{
        'badge-green': energyTips[currentTipIndex].badgeColor === 'green',
        'badge-orange': energyTips[currentTipIndex].badgeColor === 'orange',
        'badge-blue': energyTips[currentTipIndex].badgeColor === 'blue'
      }">
        {{ energyTips[currentTipIndex].category }}
      </span>

      <div class="navigation-hstack">
        <button
          class="icon-button"
          (click)="handlePrevTip()"
          aria-label="Previous tip"
          [ngStyle]="{'color': accentColor}"
        >
          <fa-icon [icon]="faArrowLeft"></fa-icon>
        </button>
        <button
          class="icon-button"
          (click)="handleNextTip()"
          aria-label="Next tip"
        >
          <fa-icon [icon]="faArrowRight"></fa-icon>
        </button>
      </div>
    </div>
  </div>
</div>
